#%RAML 1.0 SecurityScheme
description: |
  OAuth 1.0 continues to be supported for all API requests, but OAuth 2.0 is now preferred.
type: OAuth 1.0
settings:
  requestTokenUri: https://example.com/uas/oauth/requestToken
  authorizationUri: https://example.com/uas/oauth/authenticate
  tokenCredentialsUri: https://example.com/uas/oauth/accessToken
